CREATE TABLE SCA_Data(

	Page_Number			CHAR(4)		NOT NULL 	UNIQUE, 
    Defendant			VARCHAR(25), 
    Case_Status			VARCHAR(25), 
    Filing_Date			DATE, 
    Close_Date			DATE, 
    Case_Summary		VARCHAR(225), 
    Sector				VARCHAR(25), 
    Industry			VARCHAR(25), 
    Ticker_Symbol		VARCHAR(10), 
    Trading_Status		VARCHAR(25), 
    Headquarters		VARCHAR(25), 
    Company_Market		VARCHAR(25), 
    First_Court			VARCHAR(25), 
    First_Docket		VARCHAR(25), 
    First_Judge			VARCHAR(25), 
    First_Date_Filed	DATE, 
    Class_Period_Start	DATE, 
    Class_Period_End	DATE, 
    Ref_Docket			VARCHAR(25), 
	Ref_Judge			VARCHAR(25), 
    Ref_Date_Filed		DATE, 
    